import Head from "next/head";

import MainLayout from "@/layouts/main-layout";
import landingHeroImage from "@/assets/images/landing-hero-image.png";
import AppLogo from "@/components/app-logo";
import Image from "next/image";

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-20 p-5 md:px-14">
        <header className="my-5 grid place-items-center space-y-5 text-center">
          <AppLogo isLarge />
          <h1 className="text-title-lg-4">
            Moscow clothing brand that doesn&apos;t limit itself to the
            framework of any concepts
          </h1>
        </header>
        <div>
          <Image
            className="aspect-square h-full w-full object-cover lg:aspect-auto"
            src={landingHeroImage}
            alt="Landing Hero Banner"
          />
        </div>
      </main>
    </MainLayout>
  );
}
